#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <sys/types.h>
#include <sys/wait.h>
int main()
{
    int fd[2];
    pid_t pid;
    char buffer[100];
    char message[] = "Data generated by parent process";
    pipe(fd);
    pid = fork();
    if(pid == 0)
    {
        close(fd[1]);
        read(fd[0], buffer, sizeof(buffer));
        printf("Child received: %s\n", buffer);
        close(fd[0]);
    }
    else
    {
        close(fd[0]);
        write(fd[1], message, strlen(message) + 1);
        printf("Parent sent: %s\n", message);
        close(fd[1]);
        wait(NULL);
        printf("Communication completed successfully\n");
    }
    return 0;
}
